name: Bug
description: 버그가 발생할 경우 사용한다.
labels: ["Type: Bug"]
assignees:
body:
  - type: markdown
    attributes:
      value: |
        버그 이슈를 공유해주셔서 감사합니다!
  - type: textarea
    id: what-happened
    attributes:
      label: 발생한 버그에 대해서 설명해주세요!
      description: 간단하게 작성하셔도 좋고, 상세하게 작성하면 더 좋습니다.
      placeholder: ex) 로그인 버튼 클릭시 500에러가 발생한다.
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: 예외 메시지 (Optional)
      description: Please copy and paste any relevant log output.
      render: shell
  - type: dropdown
    id: version
    attributes:
      label: Server Version (Optional)
      description: 개발/운영 버전 발생 여부
      multiple: true
      options:
        - prod
        - dev
  - type: dropdown
    id: OS
    attributes:
      label: OS Version (Optional)
      multiple: true
      options:
        - IOS
        - Android

