name: Feature
description: 새로운 기능을 구현할 경우 사용한다.
labels: ["Type: Feature"]
body:
  - type: dropdown
    id: is-required
    attributes:
      label: 필수 여부
      options:
        - required
        - optional
    validations:
      required: true
  - type: textarea
    id: objective
    attributes:
      label: 구현 목표
      description: 구현해야하는 기획 의도와 내용을 적어주시면 됩니다.
      value: "> "
  - type: textarea
    id: todo-list
    attributes:
      label: 작업 상세 내용
      description: 작업 목록 또는 내용을 작성해주세요.
      value: "- [] "
    validations:
      required: true
  - type: textarea
    id: references
    attributes:
      label: 참고 사항 (Optional)
      description: 기획 링크 등 참고할만한 것들을 추가해주세요!